\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={STAT432 Assignment 2},
            pdfauthor={Rory Sarten 301005654},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{STAT432 Assignment 2}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Rory Sarten 301005654}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{21 August 2020}


\begin{document}
\maketitle

\subsection{Question 1}\label{question-1}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\item
\end{enumerate}

These are independent binomial processes (despite happening in
sequence), so the three trapping occasions can be denoted:

\(n_1 \sim Binomial(N, \theta) = \binom{N}{n_{1}} \theta^{n_1} (1 - \theta)^{N - n_1}\)

\(n_2 \sim Binomial(N - n_1, \theta) = \binom{N - n_1}{n_{2}} \theta^{n_2} (1 - \theta)^{N - n_1 - n_2}\)

\(n_3 \sim Binomial(N - n_1 - n_2, \theta) = \binom{N - n_1 - n_2}{n_{3}} \theta^{n_3} (1 - \theta)^{N - n_1 - n_2 - n_3}\)

So the probability of catching \(n_1 + n_2 + n_3\) rats is given by

\(Binomial(N, \theta) \times Binomial(N - n_1, \theta) \times Binomial(N - n_1 - N-2, \theta)\)

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\item
\end{enumerate}

\(\begin{aligned}\ell(N,\theta) = &\ln [ \dfrac{N!}{n_1(N-n_1)!}\theta^{n_1}(1-\theta)^{N-n_1} \\& \times\dfrac{(N-n_1)!}{n_2(N-n_1-n_2)!}\theta^{n_2}(1-\theta)^{N-n_1-n_2} \\& \times\dfrac{(N-n_1-n_2)!}{n_3(N-n_1-n_2-n_3)!}\theta^{n_3}(1-\theta)^{N-n_1-n_2-n_3}]\end{aligned}\)

\(\begin{aligned}\ell(N,\theta) = & \ln N! - [\ln n_1 + \ln (N-n_1)] + n_1 \ln \theta + (N-n_1)\ln (1 - \theta) +\\&\ln (N-n_1)! - [\ln n_2 + \ln (N-n_1-n_2)] + n_2 \ln \theta + (N-n_1-n_2)\ln (1 - \theta) + \\&\ln (N-n_1-n_2)! - [\ln n_3 + \ln (N-n_1-n_2-n_3)] + n_3 \ln \theta + (N-n_1-n_2-n_3)\ln (1 - \theta)\end{aligned}\)

We can reduce the components

\(n_1\ln\theta + n_2\ln\theta + n_3\ln\theta = (n_1 + n_2 + n_3)\ln\theta\)

\((N-n_1)\ln(1-\theta)+(N-n_1-n_2)\ln(1-\theta)+(N-n_1-n_2-n_3)\ln(1-\theta) = (3N-3n_1-2n_2-n_3)\ln(1-\theta)\)

\(\ln N!+\ln(N-n_1)! ...\)

Gives

\[\ln N! - \ln(N-n_1-n_2-n_3)! + (n_1+n_2+n_3)\ln\theta + (3N-3n_1-2n_2-n_3)\ln(1-\theta)\]

finish that bit of algebra somehow

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{llfunc <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(par, n1, n2, n3) \{}
\NormalTok{  N <-}\StringTok{ }\NormalTok{par[}\DecValTok{1}\NormalTok{]}
\NormalTok{  theta <-}\StringTok{ }\NormalTok{par[}\DecValTok{2}\NormalTok{]}
  \KeywordTok{lfactorial}\NormalTok{(N) }\OperatorTok{-}\StringTok{ }\KeywordTok{lfactorial}\NormalTok{(N }\OperatorTok{-}\StringTok{ }\NormalTok{n1 }\OperatorTok{-}\StringTok{ }\NormalTok{n2 }\OperatorTok{-}\StringTok{ }\NormalTok{n3) }\OperatorTok{+}
\StringTok{    }\KeywordTok{sum}\NormalTok{(n1, n2, n3)}\OperatorTok{*}\KeywordTok{log}\NormalTok{(theta) }\OperatorTok{+}\StringTok{ }
\StringTok{    }\NormalTok{(}\DecValTok{3}\OperatorTok{*}\NormalTok{N }\OperatorTok{-}\StringTok{ }\DecValTok{3}\OperatorTok{*}\NormalTok{n1 }\OperatorTok{-}\StringTok{ }\DecValTok{2}\OperatorTok{*}\NormalTok{n2 }\OperatorTok{-}\StringTok{ }\NormalTok{n3)}\OperatorTok{*}\KeywordTok{log}\NormalTok{(}\DecValTok{1} \OperatorTok{-}\StringTok{ }\NormalTok{theta)}
\NormalTok{\}}

\NormalTok{n1 <-}\StringTok{ }\NormalTok{82L}
\NormalTok{n2 <-}\StringTok{ }\NormalTok{54L}
\NormalTok{n3 <-}\StringTok{ }\NormalTok{23L}
\NormalTok{## since N >= n1 + n2 + n3}
\NormalTok{N_}\DecValTok{0}\NormalTok{ <-}\StringTok{ }\NormalTok{n1 }\OperatorTok{+}\StringTok{ }\NormalTok{n2 }\OperatorTok{+}\StringTok{ }\NormalTok{n3}
\NormalTok{par_start <-}\StringTok{ }\KeywordTok{c}\NormalTok{(N_}\DecValTok{0}\NormalTok{, }\FloatTok{0.5}\NormalTok{)}

\NormalTok{optim_fit <-}\StringTok{ }\KeywordTok{optim}\NormalTok{(}\DataTypeTok{par =}\NormalTok{ par_start,}
                   \DataTypeTok{fn =}\NormalTok{ llfunc,}
                   \DataTypeTok{n1 =}\NormalTok{ n1, }\DataTypeTok{n2 =}\NormalTok{ n2, }\DataTypeTok{n3 =}\NormalTok{ n3,}
                   \DataTypeTok{lower =} \KeywordTok{c}\NormalTok{(N_}\DecValTok{0}\NormalTok{, }\FloatTok{1e-4}\NormalTok{),}
                   \DataTypeTok{upper =} \KeywordTok{c}\NormalTok{(}\OtherTok{Inf}\NormalTok{, }\DecValTok{1}\NormalTok{),}
                   \DataTypeTok{method =} \StringTok{"L-BFGS-B"}\NormalTok{,}
                   \DataTypeTok{control =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{fnscale =} \OperatorTok{-}\DecValTok{1}\NormalTok{),}
                   \DataTypeTok{hessian =} \OtherTok{TRUE}\NormalTok{)}

\NormalTok{MLE <-}\StringTok{ }\NormalTok{optim_fit}\OperatorTok{$}\NormalTok{par}
\NormalTok{SE <-}\StringTok{ }\KeywordTok{sqrt}\NormalTok{(}\KeywordTok{diag}\NormalTok{(}\KeywordTok{solve}\NormalTok{(}\OperatorTok{-}\NormalTok{optim_fit}\OperatorTok{$}\NormalTok{hessian)))}
\NormalTok{LowerBound <-}\StringTok{ }\NormalTok{MLE }\OperatorTok{-}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{) }\OperatorTok{*}\StringTok{ }\NormalTok{SE}
\NormalTok{UpperBound <-}\StringTok{ }\NormalTok{MLE }\OperatorTok{+}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{) }\OperatorTok{*}\StringTok{ }\NormalTok{SE}
\NormalTok{results <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(MLE, SE, LowerBound, UpperBound) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{round}\NormalTok{(}\DecValTok{2}\NormalTok{)}
\KeywordTok{rownames}\NormalTok{(results) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"N"}\NormalTok{, }\StringTok{"theta"}\NormalTok{)}
\NormalTok{results}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          MLE    SE LowerBound UpperBound
## N     189.43 13.23     163.49     215.36
## theta   0.45  0.06       0.34       0.57
\end{verbatim}

The maximum likelihood point \(\hat{N} = 189.43\) with confidence
interval \((163.49, 215.36)\)

The maximum likelihood point \(\hat{\theta} = 0.45\) with confidence
interval \((0.34, 0.57)\)

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{3}
\item
\end{enumerate}

Contour map of \((N, \theta)\) surface

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n_vals <-}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DataTypeTok{from =}\NormalTok{ n1}\OperatorTok{+}\NormalTok{n2}\OperatorTok{+}\NormalTok{n3, }\DataTypeTok{to =} \DecValTok{260}\NormalTok{, }\DataTypeTok{length =} \DecValTok{100}\NormalTok{)}
\NormalTok{theta_vals <-}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DataTypeTok{from =} \FloatTok{0.2}\NormalTok{, }\DataTypeTok{to =} \FloatTok{0.7}\NormalTok{, }\DataTypeTok{length =} \DecValTok{100}\NormalTok{)}

\NormalTok{combos <-}\StringTok{ }\KeywordTok{expand.grid}\NormalTok{(n_vals, theta_vals)}
\NormalTok{surface <-}\StringTok{ }\KeywordTok{apply}\NormalTok{(}\KeywordTok{expand.grid}\NormalTok{(n_vals, theta_vals), }\DecValTok{1}\NormalTok{, llfunc, }\DataTypeTok{n1 =}\NormalTok{ n1, }\DataTypeTok{n2 =}\NormalTok{ n2, }\DataTypeTok{n3 =}\NormalTok{ n3) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{round}\NormalTok{(}\DecValTok{2}\NormalTok{)}
\NormalTok{outcome <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(combos, surface)}
\KeywordTok{names}\NormalTok{(outcome) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"N"}\NormalTok{, }\StringTok{"theta"}\NormalTok{, }\StringTok{"value"}\NormalTok{)}

\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ outcome, }\DataTypeTok{mapping =} \KeywordTok{aes}\NormalTok{(N, theta)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_contour}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{z =}\NormalTok{ value),}
               \DataTypeTok{breaks =} \KeywordTok{seq}\NormalTok{(}\DataTypeTok{from =} \KeywordTok{min}\NormalTok{(outcome}\OperatorTok{$}\NormalTok{value), }\DataTypeTok{to =} \KeywordTok{max}\NormalTok{(outcome}\OperatorTok{$}\NormalTok{value), }\DataTypeTok{by =} \DecValTok{12}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_contour}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{z =}\NormalTok{ value,}
                   \DataTypeTok{colour =} \KeywordTok{factor}\NormalTok{(..level.. }\OperatorTok{==}\StringTok{ }\KeywordTok{max}\NormalTok{(surface) }\OperatorTok{-}\StringTok{ }\FloatTok{1.92}\NormalTok{,}
                                   \DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(F, T),}
                                   \DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"Single 95% CI "}\NormalTok{))),}
               \DataTypeTok{breaks =} \KeywordTok{max}\NormalTok{(surface) }\OperatorTok{-}\StringTok{ }\FloatTok{1.92}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_contour}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{z =}\NormalTok{ value,}
                   \DataTypeTok{colour =} \KeywordTok{factor}\NormalTok{(..level.. }\OperatorTok{==}\StringTok{ }\KeywordTok{max}\NormalTok{(surface) }\OperatorTok{-}\StringTok{ }\DecValTok{3}\NormalTok{,}
                                   \DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(F, T),}
                                   \DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"Joint 95% CI "}\NormalTok{))),}
               \DataTypeTok{breaks =} \KeywordTok{max}\NormalTok{(surface) }\OperatorTok{-}\StringTok{ }\DecValTok{3}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping =} \KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ MLE[}\DecValTok{1}\NormalTok{], }\DataTypeTok{y =}\NormalTok{ MLE[}\DecValTok{2}\NormalTok{]), }\DataTypeTok{colour =} \StringTok{"darkblue"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{colour =} \StringTok{"Of interest:"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\CommentTok{#ggtitle("Contour map of (N, \textbackslash{}u03B8) surface") +}
\StringTok{  }\CommentTok{#ylab("\textbackslash{}u03B8") +}
\StringTok{  }\KeywordTok{theme_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{assignment2_files/figure-latex/contour_map-1.pdf}

\pagebreak

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{4}
\item
\end{enumerate}

\(\dfrac{\partial \ell}{\partial\theta} = \dfrac{n_1+n_2+n_3}{\theta} - \dfrac{3N-3n_1-2n_2-n_3}{1-\theta}\)

\$ =
\dfrac{(n_1+n_2+n_3) - (n_1+n_2+n_3)\theta -(3N-3n_1-2n_2-n_3)\theta}{\theta(1-\theta)}
\$

Setting this to \(0\)

\$ (n\_1+n\_2+n\_3) - {[}(n\_1+n\_2+n\_3)
+(3N-3n\_1-2n\_2-n\_3){]}\theta = 0\$

\$ {[}(n\_1+n\_2+n\_3) +(3N-3n\_1-2n\_2-n\_3){]}\theta =
(n\_1+n\_2+n\_3)\$

\$ \theta = \dfrac{(n_1+n_2+n_3)}{(n_1+n_2+n_3)+(3N-3n_1-2n_2-n_3)} =
\dfrac{(n_1+n_2+n_3)}{3N-3n_1+n_1-2n_2+n_2-n_3+n_3}\$

\$ \hat{\theta} = \dfrac{n_1+n_2+n_3}{3N - 2n_1-n_2}\$

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{5}
\item
\end{enumerate}

We have

\$ \hat{\theta} = \dfrac{n_1+n_2+n_3}{3N - 2n_1-n_2}\$

and

\$ 1-\hat{\theta} = \dfrac{3N - 2n_1-n_2}{3N - 2n_1-n_2} -
\dfrac{n_1+n_2+n_3}{3N - 2n_1-n_2} =
\dfrac{3N - 3n_1-2n_2-n_3}{3N - 2n_1-n_2}\$

So we can rewrite the original kernel of the log likelihood in terms of
\(N\) as:

\(\begin{aligned}\ell(N) =& \ln N!-\ln (N-n_1-n_2-n_3)!+(n_1+n_2+n_3)\ln \left(\dfrac{n_1+n_2+n_3}{3N - 2n_1-n_2}\right) + \\&(3N-3n_1-2n_2-n_3)\ln \left(\dfrac{3N - 3n_1-2n_2-n_3}{3N - 2n_1-n_2}\right)\end{aligned}\)

\(\begin{aligned}\ell(N)=&\ln N!-\ln N!-\ln (N-n_1-n_2-n_3)!+ \\&(n_1+n_2+n_3)\ln (n_1+n_2+n_3)-(n_1+n_2+n_3)\ln(3N-2n_1-n_2)+\\&(3N-3n_1-2n_2-n_3)\ln (3N - 3n_1-2n_2-n_3)-(3N-3n_1-2n_2-n_3)\ln(3N -2n_1-n_2)\end{aligned}\)

\(\begin{aligned}\ell(N)=&\ln N!-\ln N!-\ln (N-n_1-n_2-n_3)!+ \\&(3N-3n_1-2n_2-n_3)\ln(3N - 3n_1-2n_2-n_3) - \\&(n_1+n_2+n_3+3N-3n_1-2n_2-n_3)\ln (3N-2n_1-n_2)\end{aligned}\)

Therefore

\(\begin{aligned}\ell(N)=&\ln N!-\ln N!-\ln (N-n_1-n_2-n_3)!+ \\&(3N-3n_1-2n_2-n_3)\ln(3N - 3n_1-2n_2-n_3) - \\&(3N-2n_1-n_2)\ln (3N-2n_1-n_2)\end{aligned}\)

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{6}
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{llfunc_N <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(N, n1, n2, n3) \{}
  \KeywordTok{lfactorial}\NormalTok{(N) }\OperatorTok{-}\StringTok{ }\KeywordTok{lfactorial}\NormalTok{(N }\OperatorTok{-}\StringTok{ }\NormalTok{n1 }\OperatorTok{-}\StringTok{ }\NormalTok{n2 }\OperatorTok{-}\StringTok{ }\NormalTok{n3) }\OperatorTok{+}
\StringTok{    }\NormalTok{(}\DecValTok{3}\OperatorTok{*}\NormalTok{N }\OperatorTok{-}\StringTok{ }\DecValTok{3}\OperatorTok{*}\NormalTok{n1 }\OperatorTok{-}\StringTok{ }\DecValTok{2}\OperatorTok{*}\NormalTok{n2 }\OperatorTok{-}\StringTok{ }\NormalTok{n3)}\OperatorTok{*}\KeywordTok{log}\NormalTok{(}\DecValTok{3}\OperatorTok{*}\NormalTok{N }\OperatorTok{-}\StringTok{ }\DecValTok{3}\OperatorTok{*}\NormalTok{n1 }\OperatorTok{-}\StringTok{ }\DecValTok{2}\OperatorTok{*}\NormalTok{n2 }\OperatorTok{-}\StringTok{ }\NormalTok{n3) }\OperatorTok{-}
\StringTok{    }\NormalTok{(}\DecValTok{3}\OperatorTok{*}\NormalTok{N }\OperatorTok{-}\StringTok{ }\DecValTok{2}\OperatorTok{*}\NormalTok{n1 }\OperatorTok{-}\StringTok{ }\NormalTok{n2)}\OperatorTok{*}\KeywordTok{log}\NormalTok{(}\DecValTok{3}\OperatorTok{*}\NormalTok{N }\OperatorTok{-}\StringTok{ }\DecValTok{2}\OperatorTok{*}\NormalTok{n1 }\OperatorTok{-}\StringTok{ }\NormalTok{n2)}
\NormalTok{\}}

\NormalTok{n1 <-}\StringTok{ }\NormalTok{82L}
\NormalTok{n2 <-}\StringTok{ }\NormalTok{54L}
\NormalTok{n3 <-}\StringTok{ }\NormalTok{23L}
\NormalTok{## since N >= n1 + n2 + n3}
\NormalTok{N_}\DecValTok{0}\NormalTok{ <-}\StringTok{ }\NormalTok{n1 }\OperatorTok{+}\StringTok{ }\NormalTok{n2 }\OperatorTok{+}\StringTok{ }\NormalTok{n3}
\NormalTok{N_start <-}\StringTok{ }\KeywordTok{c}\NormalTok{(N_}\DecValTok{0}\NormalTok{)}

\NormalTok{optim_fit <-}\StringTok{ }\KeywordTok{optim}\NormalTok{(}\DataTypeTok{par =}\NormalTok{ N_start,}
                   \DataTypeTok{fn =}\NormalTok{ llfunc_N,}
                   \DataTypeTok{n1 =}\NormalTok{ n1, }\DataTypeTok{n2 =}\NormalTok{ n2, }\DataTypeTok{n3 =}\NormalTok{ n3,}
                   \DataTypeTok{lower =} \KeywordTok{c}\NormalTok{(N_}\DecValTok{0}\NormalTok{, }\FloatTok{1e-4}\NormalTok{),}
                   \DataTypeTok{upper =} \KeywordTok{c}\NormalTok{(}\OtherTok{Inf}\NormalTok{, }\DecValTok{1}\NormalTok{),}
                   \DataTypeTok{method =} \StringTok{"L-BFGS-B"}\NormalTok{,}
                   \DataTypeTok{control =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{fnscale =} \OperatorTok{-}\DecValTok{1}\NormalTok{),}
                   \DataTypeTok{hessian =} \OtherTok{TRUE}\NormalTok{)}

\NormalTok{N_hat <-}\StringTok{ }\NormalTok{optim_fit}\OperatorTok{$}\NormalTok{par}
\NormalTok{log_max <-}\StringTok{ }\NormalTok{optim_fit}\OperatorTok{$}\NormalTok{value}

\NormalTok{## calculate 95% CI}
\NormalTok{crit_point <-}\StringTok{ }\NormalTok{log_max }\OperatorTok{-}\StringTok{ }\FloatTok{0.5} \OperatorTok{*}\StringTok{ }\KeywordTok{qchisq}\NormalTok{(}\FloatTok{0.95}\NormalTok{, }\DataTypeTok{df =} \DecValTok{1}\NormalTok{)}

\NormalTok{ci_func <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(critical_value, ...) \{}
  \KeywordTok{llfunc_N}\NormalTok{(...) }\OperatorTok{-}\StringTok{ }\NormalTok{critical_value}
\NormalTok{\}}

\NormalTok{lower <-}\StringTok{ }\KeywordTok{uniroot}\NormalTok{(ci_func, }\DataTypeTok{interval =} \KeywordTok{c}\NormalTok{(N_}\DecValTok{0}\NormalTok{, N_hat), }
                 \DataTypeTok{n1 =}\NormalTok{ n1, }\DataTypeTok{n2 =}\NormalTok{ n2, }\DataTypeTok{n3 =}\NormalTok{ n3, }
                 \DataTypeTok{critical_value =}\NormalTok{ crit_point)}\OperatorTok{$}\NormalTok{root}
\NormalTok{upper <-}\StringTok{ }\KeywordTok{uniroot}\NormalTok{(ci_func, }\DataTypeTok{interval =} \KeywordTok{c}\NormalTok{(N_hat, }\DecValTok{300}\NormalTok{), }
                 \DataTypeTok{n1 =}\NormalTok{ n1, }\DataTypeTok{n2 =}\NormalTok{ n2, }\DataTypeTok{n3 =}\NormalTok{ n3, }
                 \DataTypeTok{critical_value =}\NormalTok{ crit_point)}\OperatorTok{$}\NormalTok{root}

\NormalTok{n_vals <-}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DataTypeTok{from =}\NormalTok{ n1}\OperatorTok{+}\NormalTok{n2}\OperatorTok{+}\NormalTok{n3, }\DataTypeTok{to =} \DecValTok{260}\NormalTok{, }\DataTypeTok{length =} \DecValTok{100}\NormalTok{)}
\NormalTok{data <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ n_vals,}
                   \DataTypeTok{y =} \KeywordTok{llfunc_N}\NormalTok{(n_vals, }\DataTypeTok{n1 =}\NormalTok{ n1, }\DataTypeTok{n2 =}\NormalTok{ n2, }\DataTypeTok{n3 =}\NormalTok{ n3))}

\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ data, }\DataTypeTok{mapping =} \KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ x, }\DataTypeTok{y =}\NormalTok{ y)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_line}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ N_hat, }\DataTypeTok{y =}\NormalTok{ log_max))}
\end{Highlighting}
\end{Shaded}

\includegraphics{assignment2_files/figure-latex/solve_g-1.pdf}


\end{document}
